<?php
require_once '../includes/config.php'; require_once '../includes/auth.php'; require_once '../includes/functions.php';
$user=require_auth();$current_page='admin-notifications';$page_title='Bildirimlerim';
include '../includes/header.php';include '../includes/sidebar.php';
?>
<div class="container-fluid"><div class="page-header"><div><h2>Bildirimlerim</h2><p class="text-muted mb-0">İşlem bekleyen yönetim olayları.</p></div><button class="btn btn-outline-primary" id="readAll">Tümünü Okundu Yap</button></div>
<div class="card"><div class="card-body"><div class="row g-2 mb-3"><div class="col-md-3"><select id="filter" class="form-select"><option value="all">Tümü</option><option value="unread">Okunmamış</option><option value="question_report">Soru Bildirimleri</option><option value="support">Destek</option><option value="community_report">Topluluk</option><option value="subscription">Abonelik</option><option value="referral">Referans</option><option value="push">Bildirim Gönderimi</option><option value="rewarded_ad">Reklam Doğrulama</option><option value="critical">Kritik</option><option value="high">Yüksek</option></select></div><div class="col-md-6"><input id="search" class="form-control" placeholder="Bildirimlerde ara"></div><div class="col-md-2"><button id="apply" class="btn btn-primary w-100">Filtrele</button></div></div><div id="items" class="d-grid gap-2"><div class="text-muted">Yükleniyor...</div></div></div></div></div>
<?php $extra_js=<<<'JS'
<script>$(function(){const ep='../ajax/admin-notifications.php',esc=v=>$('<div>').text(v??'').html();const sev={critical:'danger',high:'warning',normal:'primary',low:'secondary'};async function load(){const r=await window.appAjax({url:ep,data:{action:'list',filter:$('#filter').val(),search:$('#search').val()},dataType:'json'});const a=r.data?.items||[];$('#items').html(a.map(x=>`<div class="card ${Number(x.is_read)?'opacity-75':'border-primary'}"><div class="card-body d-flex gap-3 align-items-start"><i class="bi bi-bell-fill text-${sev[x.severity]||'primary'} fs-4"></i><div class="flex-grow-1"><div class="d-flex flex-wrap gap-2"><strong>${esc(x.title)}</strong><span class="badge text-bg-${sev[x.severity]||'primary'}">${esc(x.severity)}</span>${Number(x.is_read)?'':'<span class="badge text-bg-info">Yeni</span>'}</div><p class="mb-1 mt-1">${esc(x.message||'')}</p><small class="text-muted">${esc(x.created_at)}</small></div><div class="d-flex flex-column gap-1"><a class="btn btn-sm btn-primary go" data-id="${esc(x.id)}" href="${esc(x.target_url)}">Kayda Git</a><button class="btn btn-sm btn-outline-success state" data-id="${esc(x.id)}" data-status="resolved">Çözüldü</button><button class="btn btn-sm btn-outline-secondary state" data-id="${esc(x.id)}" data-status="archived">Arşivle</button></div></div></div>`).join('')||'<div class="text-muted p-4 text-center">Bildirim bulunamadı.</div>');}
$(document).on('click','.go',function(){navigator.sendBeacon(ep,new URLSearchParams({action:'mark_read',id:$(this).data('id')}));});$(document).on('click','.state',async function(){await window.appAjax({url:ep,method:'POST',data:{action:'set_status',id:$(this).data('id'),status:$(this).data('status')},dataType:'json'});load();});$('#apply,#filter').on('click change',load);$('#readAll').on('click',async()=>{await window.appAjax({url:ep,method:'POST',data:{action:'mark_all_read'},dataType:'json'});load();});load();});</script>
JS; include '../includes/footer.php'; ?>
