<?php
require_once '../includes/config.php';
require_once '../includes/auth.php';
require_once '../includes/functions.php';
$user=require_auth(); $current_page='visitor-analytics'; $page_title='Ziyaretçi Analizi';
$extra_head='\n<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">\n<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>';
include '../includes/header.php'; include '../includes/sidebar.php';
?>
<style>
.va-map{height:480px;border-radius:18px;overflow:hidden;background:#dbeafe}.va-live{display:inline-block;width:9px;height:9px;border-radius:50%;background:#22c55e;box-shadow:0 0 0 5px #22c55e22}.va-metric{font-size:1.75rem;font-weight:750}.va-list{max-height:390px;overflow:auto}.va-map-marker{display:flex;align-items:center;justify-content:center;border:2px solid #fff;border-radius:50%;background:#0284c7;color:#fff;font-weight:800;box-shadow:0 0 0 6px #0284c733,0 4px 18px #0f172a55;cursor:pointer}.va-map-marker.city{background:#7c3aed;box-shadow:0 0 0 5px #7c3aed33,0 4px 16px #0f172a44}.leaflet-tooltip.va-tooltip{border:0;border-radius:9px;background:#0f172a;color:#fff;box-shadow:0 5px 18px #0004}.va-map-empty{position:absolute;z-index:500;left:50%;top:16px;transform:translateX(-50%);padding:8px 14px;border-radius:10px;background:#fff;color:#64748b;box-shadow:0 3px 14px #0002}
</style>
<div class="container-fluid">
 <div class="page-header d-flex justify-content-between align-items-start"><div><h2>Ziyaretçi Analizi</h2><p class="text-muted mb-0">Web sitesi ve portal trafiğinin gizlilik odaklı canlı görünümü</p></div><select id="range" class="form-select" style="width:auto"><option value="today">Bugün</option><option value="7d" selected>Son 7 gün</option><option value="30d">Son 30 gün</option><option value="90d">Son 90 gün</option></select></div>
 <div class="row g-3 mb-3" id="metrics"></div>
 <div class="card soft-card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><strong><span class="va-live me-2"></span>Anlık Ziyaretçi Haritası</strong><div class="d-flex align-items-center gap-2"><button type="button" id="worldView" class="btn btn-sm btn-outline-primary"><i class="bi bi-globe2 me-1"></i>Dünya görünümü</button><span id="updated" class="text-muted small"></span></div></div><div class="card-body"><div class="va-map" id="map"></div><div class="small text-muted mt-2">Ülke balonuna tıklayarak yakınlaşın; yakın görünümde şehir bazlı aktif ziyaretçi sayıları gösterilir.</div></div></div>
 <div class="row g-3 mb-3"><div class="col-xl-8"><div class="card soft-card h-100"><div class="card-header"><strong>Ziyaret Trendi</strong></div><div class="card-body"><canvas id="trendChart" height="105"></canvas></div></div></div><div class="col-xl-4"><div class="card soft-card h-100"><div class="card-header"><strong>Cihaz Dağılımı</strong></div><div class="card-body"><canvas id="deviceChart"></canvas></div></div></div></div>
 <div class="row g-3 mb-3"><div class="col-lg-4"><div class="card soft-card h-100"><div class="card-header"><strong>Ülkeler</strong></div><div class="card-body va-list" id="countries"></div></div></div><div class="col-lg-4"><div class="card soft-card h-100"><div class="card-header"><strong>Trafik Kaynakları</strong></div><div class="card-body va-list" id="sources"></div></div></div><div class="col-lg-4"><div class="card soft-card h-100"><div class="card-header"><strong>En Çok Görüntülenen Sayfalar</strong></div><div class="card-body va-list" id="pages"></div></div></div></div>
 <div class="card soft-card"><div class="card-header"><strong>Son Ziyaret Oturumları</strong></div><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Ziyaretçi</th><th>Konum</th><th>Cihaz</th><th>Son Sayfa</th><th>Sayfa</th><th>Son Aktivite</th></tr></thead><tbody id="recent"><tr><td colspan="6">Yükleniyor…</td></tr></tbody></table></div></div>
</div>
<?php $extra_js=<<<'JS'
<script>
$(function(){let trendChart,deviceChart,map,mapLayer,mapActive=[];const esc=v=>$('<div>').text(v??'').html();const list=(rows,valueKey='value')=>(rows||[]).map(x=>`<div class="d-flex justify-content-between border-bottom py-2"><span>${esc(x.label||'Bilinmiyor')}</span><strong>${Number(x[valueKey]||0).toLocaleString('tr-TR')}</strong></div>`).join('')||'<span class="text-muted">Veri yok</span>';
function initMap(){if(map||typeof L==='undefined')return;map=L.map('map',{worldCopyJump:true,minZoom:2,maxBoundsViscosity:.6}).setView([25,15],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> katkıcıları'}).addTo(map);mapLayer=L.layerGroup().addTo(map);map.on('zoomend',drawMap);$('#worldView').on('click',()=>map.flyTo([25,15],2,{duration:.7}))}
function markerIcon(count,city){const size=Math.min(city?46:58,(city?28:34)+Math.sqrt(count)*7);return L.divIcon({className:'',html:`<div class="va-map-marker ${city?'city':''}" style="width:${size}px;height:${size}px">${count}</div>`,iconSize:[size,size],iconAnchor:[size/2,size/2]})}
function drawMap(){if(!map||!mapLayer)return;mapLayer.clearLayers();$('.va-map-empty').remove();const valid=mapActive.filter(x=>Number.isFinite(Number(x.latitude))&&Number.isFinite(Number(x.longitude)));if(!valid.length){$('#map').append('<div class="va-map-empty">Şu anda konumu belirlenmiş aktif ziyaretçi yok</div>');return}const cityMode=map.getZoom()>4,groups={};valid.forEach(x=>{const lat=Number(x.latitude),lng=Number(x.longitude);const key=cityMode?`${x.country_code||''}|${x.city_name||x.region_name||''}|${lat.toFixed(2)}|${lng.toFixed(2)}`:(x.country_code||x.country_name||`${lat},${lng}`);if(!groups[key])groups[key]={...x,count:0,latSum:0,lngSum:0};groups[key].count++;groups[key].latSum+=lat;groups[key].lngSum+=lng});Object.values(groups).forEach(x=>{const lat=x.latSum/x.count,lng=x.lngSum/x.count;const label=cityMode?(x.city_name||x.region_name||'Şehir bilinmiyor'):(x.country_name||'Ülke bilinmiyor');const marker=L.marker([lat,lng],{icon:markerIcon(x.count,cityMode)}).bindTooltip(`<strong>${esc(label)}</strong><br>${x.count} aktif ziyaretçi`,{direction:'top',className:'va-tooltip',offset:[0,-12]});if(!cityMode)marker.on('click',()=>map.flyTo([lat,lng],x.country_code==='TR'?6:5,{duration:.8}));marker.addTo(mapLayer)})}
function renderMap(active){mapActive=active||[];initMap();drawMap()}
function chart(data){const labels=(data||[]).map(x=>x.day),visitors=(data||[]).map(x=>x.visitors),views=(data||[]).map(x=>x.pageviews);if(trendChart)trendChart.destroy();trendChart=new Chart($('#trendChart'),{type:'line',data:{labels,datasets:[{label:'Ziyaretçi',data:visitors,borderColor:'#38bdf8',tension:.35},{label:'Sayfa görüntüleme',data:views,borderColor:'#8b5cf6',tension:.35}]},options:{responsive:true,maintainAspectRatio:false}})}
async function load(){const r=await $.getJSON('../ajax/visitor-analytics.php',{range:$('#range').val()}).catch(()=>null);if(!r?.success){$('#recent').html('<tr><td colspan="6" class="text-danger">Veriler alınamadı. SQL migrationını kontrol edin.</td></tr>');return}const d=r.data,s=d.summary;$('#metrics').html([['Anlık',s.active_now,'bi-broadcast'],['Tekil ziyaretçi',s.visitors,'bi-people'],['Oturum',s.sessions,'bi-window-stack'],['Sayfa görüntüleme',s.pageviews,'bi-eye'],['Ort. sayfa/oturum',s.avg_pages,'bi-graph-up']].map(x=>`<div class="col-6 col-xl"><div class="card soft-card h-100"><div class="card-body"><i class="bi ${x[2]} text-primary"></i><div class="va-metric">${Number(x[1]||0).toLocaleString('tr-TR')}</div><div class="text-muted small">${x[0]}</div></div></div></div>`).join(''));renderMap(d.active);chart(d.trend);if(deviceChart)deviceChart.destroy();deviceChart=new Chart($('#deviceChart'),{type:'doughnut',data:{labels:d.devices.map(x=>x.label),datasets:[{data:d.devices.map(x=>x.value),backgroundColor:['#38bdf8','#8b5cf6','#22c55e','#f59e0b']}]},options:{plugins:{legend:{position:'bottom'}}}});$('#countries').html(list(d.countries));$('#sources').html(list(d.sources));$('#pages').html(list(d.pages,'views'));$('#recent').html(d.recent.map(x=>`<tr><td><strong>${esc(x.full_name||'Anonim')}</strong><div class="small text-muted">${x.user_id?'Kayıtlı':'Anonim'}</div></td><td>${esc(x.country_name||'Bilinmiyor')}</td><td>${esc(x.device_type)} · ${esc(x.browser_name)}<div class="small text-muted">${esc(x.os_name)}</div></td><td class="text-break">${esc(x.last_path)}</td><td>${x.pageview_count}</td><td>${esc(x.last_seen_at)}</td></tr>`).join('')||'<tr><td colspan="6">Veri yok</td></tr>');$('#updated').text('Son güncelleme: '+new Date().toLocaleTimeString('tr-TR'))}
$('#range').on('change',load);load();setInterval(load,30000);
});
</script>
JS; include '../includes/footer.php'; ?>
