<?php
require_once '../includes/config.php';
require_once '../includes/auth.php';
require_once '../includes/functions.php';
$user=require_auth(); $current_page='visitor-analytics'; $page_title='Ziyaretçi Analizi';
include '../includes/header.php'; include '../includes/sidebar.php';
?>
<style>
.va-map{position:relative;min-height:360px;border-radius:18px;overflow:hidden;background:linear-gradient(145deg,#071a33,#0b3156);isolation:isolate}.va-map:before{content:"";position:absolute;inset:8%;opacity:.28;background:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1000 500'%3E%3Cg fill='%237dd3fc'%3E%3Cellipse cx='190' cy='175' rx='125' ry='95'/%3E%3Cellipse cx='270' cy='335' rx='58' ry='125'/%3E%3Cellipse cx='505' cy='155' rx='105' ry='60'/%3E%3Cellipse cx='520' cy='300' rx='82' ry='120'/%3E%3Cellipse cx='710' cy='180' rx='190' ry='100'/%3E%3Cellipse cx='850' cy='355' rx='75' ry='45'/%3E%3C/g%3E%3C/svg%3E") center/contain no-repeat}.va-dot{position:absolute;z-index:2;transform:translate(-50%,-50%);border:2px solid #fff;border-radius:50%;background:#38bdf8;box-shadow:0 0 0 6px #38bdf833,0 0 24px #38bdf8;cursor:help}.va-live{display:inline-block;width:9px;height:9px;border-radius:50%;background:#22c55e;box-shadow:0 0 0 5px #22c55e22}.va-metric{font-size:1.75rem;font-weight:750}.va-list{max-height:390px;overflow:auto}.va-empty{position:absolute;inset:0;display:grid;place-items:center;color:#cbd5e1;z-index:1}
</style>
<div class="container-fluid">
 <div class="page-header d-flex justify-content-between align-items-start"><div><h2>Ziyaretçi Analizi</h2><p class="text-muted mb-0">Web sitesi ve portal trafiğinin gizlilik odaklı canlı görünümü</p></div><select id="range" class="form-select" style="width:auto"><option value="today">Bugün</option><option value="7d" selected>Son 7 gün</option><option value="30d">Son 30 gün</option><option value="90d">Son 90 gün</option></select></div>
 <div class="row g-3 mb-3" id="metrics"></div>
 <div class="card soft-card mb-3"><div class="card-header d-flex justify-content-between"><strong><span class="va-live me-2"></span>Anlık Ziyaretçi Haritası</strong><span id="updated" class="text-muted small"></span></div><div class="card-body"><div class="va-map" id="map"><div class="va-empty">Aktif ziyaretçi bekleniyor…</div></div></div></div>
 <div class="row g-3 mb-3"><div class="col-xl-8"><div class="card soft-card h-100"><div class="card-header"><strong>Ziyaret Trendi</strong></div><div class="card-body"><canvas id="trendChart" height="105"></canvas></div></div></div><div class="col-xl-4"><div class="card soft-card h-100"><div class="card-header"><strong>Cihaz Dağılımı</strong></div><div class="card-body"><canvas id="deviceChart"></canvas></div></div></div></div>
 <div class="row g-3 mb-3"><div class="col-lg-4"><div class="card soft-card h-100"><div class="card-header"><strong>Ülkeler</strong></div><div class="card-body va-list" id="countries"></div></div></div><div class="col-lg-4"><div class="card soft-card h-100"><div class="card-header"><strong>Trafik Kaynakları</strong></div><div class="card-body va-list" id="sources"></div></div></div><div class="col-lg-4"><div class="card soft-card h-100"><div class="card-header"><strong>En Çok Görüntülenen Sayfalar</strong></div><div class="card-body va-list" id="pages"></div></div></div></div>
 <div class="card soft-card"><div class="card-header"><strong>Son Ziyaret Oturumları</strong></div><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Ziyaretçi</th><th>Konum</th><th>Cihaz</th><th>Son Sayfa</th><th>Sayfa</th><th>Son Aktivite</th></tr></thead><tbody id="recent"><tr><td colspan="6">Yükleniyor…</td></tr></tbody></table></div></div>
</div>
<?php $extra_js=<<<'JS'
<script>
$(function(){let trendChart,deviceChart;const esc=v=>$('<div>').text(v??'').html();const list=(rows,valueKey='value')=>(rows||[]).map(x=>`<div class="d-flex justify-content-between border-bottom py-2"><span>${esc(x.label||'Bilinmiyor')}</span><strong>${Number(x[valueKey]||0).toLocaleString('tr-TR')}</strong></div>`).join('')||'<span class="text-muted">Veri yok</span>';
function renderMap(active){const map=$('#map').empty();if(!active.length){map.html('<div class="va-empty">Şu anda aktif ziyaretçi yok</div>');return}const groups={};active.forEach(x=>{if(x.latitude==null||x.longitude==null)return;const k=`${x.latitude},${x.longitude},${x.country_name||''}`;(groups[k]??={...x,count:0}).count++});Object.values(groups).forEach(x=>{const left=(Number(x.longitude)+180)/360*100,top=(90-Number(x.latitude))/180*100,size=Math.min(32,12+Math.sqrt(x.count)*6);map.append(`<span class="va-dot" style="left:${left}%;top:${top}%;width:${size}px;height:${size}px" title="${esc(x.country_name||'Bilinmiyor')}: ${x.count} aktif ziyaretçi"></span>`)})}
function chart(data){const labels=(data||[]).map(x=>x.day),visitors=(data||[]).map(x=>x.visitors),views=(data||[]).map(x=>x.pageviews);if(trendChart)trendChart.destroy();trendChart=new Chart($('#trendChart'),{type:'line',data:{labels,datasets:[{label:'Ziyaretçi',data:visitors,borderColor:'#38bdf8',tension:.35},{label:'Sayfa görüntüleme',data:views,borderColor:'#8b5cf6',tension:.35}]},options:{responsive:true,maintainAspectRatio:false}})}
async function load(){const r=await $.getJSON('../ajax/visitor-analytics.php',{range:$('#range').val()}).catch(()=>null);if(!r?.success){$('#recent').html('<tr><td colspan="6" class="text-danger">Veriler alınamadı. SQL migrationını kontrol edin.</td></tr>');return}const d=r.data,s=d.summary;$('#metrics').html([['Anlık',s.active_now,'bi-broadcast'],['Tekil ziyaretçi',s.visitors,'bi-people'],['Oturum',s.sessions,'bi-window-stack'],['Sayfa görüntüleme',s.pageviews,'bi-eye'],['Ort. sayfa/oturum',s.avg_pages,'bi-graph-up']].map(x=>`<div class="col-6 col-xl"><div class="card soft-card h-100"><div class="card-body"><i class="bi ${x[2]} text-primary"></i><div class="va-metric">${Number(x[1]||0).toLocaleString('tr-TR')}</div><div class="text-muted small">${x[0]}</div></div></div></div>`).join(''));renderMap(d.active);chart(d.trend);if(deviceChart)deviceChart.destroy();deviceChart=new Chart($('#deviceChart'),{type:'doughnut',data:{labels:d.devices.map(x=>x.label),datasets:[{data:d.devices.map(x=>x.value),backgroundColor:['#38bdf8','#8b5cf6','#22c55e','#f59e0b']}]},options:{plugins:{legend:{position:'bottom'}}}});$('#countries').html(list(d.countries));$('#sources').html(list(d.sources));$('#pages').html(list(d.pages,'views'));$('#recent').html(d.recent.map(x=>`<tr><td><strong>${esc(x.full_name||'Anonim')}</strong><div class="small text-muted">${x.user_id?'Kayıtlı':'Anonim'}</div></td><td>${esc(x.country_name||'Bilinmiyor')}</td><td>${esc(x.device_type)} · ${esc(x.browser_name)}<div class="small text-muted">${esc(x.os_name)}</div></td><td class="text-break">${esc(x.last_path)}</td><td>${x.pageview_count}</td><td>${esc(x.last_seen_at)}</td></tr>`).join('')||'<tr><td colspan="6">Veri yok</td></tr>');$('#updated').text('Son güncelleme: '+new Date().toLocaleTimeString('tr-TR'))}
$('#range').on('change',load);load();setInterval(load,30000);
});
</script>
JS; include '../includes/footer.php'; ?>
