<?php
require_once '../includes/config.php'; require_once '../includes/auth.php'; require_once '../includes/functions.php';
$user=require_auth(); $current_page='word-game-questions'; $page_title='Kelime Oyunu - Sorular';
$qualifications=$pdo->query('SELECT id,name FROM qualifications ORDER BY name ASC')->fetchAll(PDO::FETCH_ASSOC);
$categories=$pdo->query('SELECT id,name FROM word_game_categories ORDER BY order_index ASC, name ASC')->fetchAll(PDO::FETCH_ASSOC);
include '../includes/header.php'; include '../includes/sidebar.php';
?>
<div class="container-fluid">
  <div class="page-header"><div><h2>Kelime Oyunu Soru Havuzu</h2></div><div class="page-actions"><button class="btn btn-primary" id="addBtn"><i class="bi bi-plus-lg"></i> Yeni Soru Ekle</button></div></div>
  <div class="card mb-3"><div class="card-body"><div class="row g-3"><div class="col-md-3"><label class="form-label">Başlık</label><select id="fCategory" class="form-select"><option value="">Tümü</option><?php foreach($categories as $c): ?><option value="<?=htmlspecialchars($c['id'])?>"><?=htmlspecialchars($c['name'])?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Yeterlilik</label><select id="fQualification" class="form-select"><option value="">Tümü</option><?php foreach($qualifications as $q): ?><option value="<?=htmlspecialchars($q['id'])?>"><?=htmlspecialchars($q['name'])?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Durum</label><select id="fActive" class="form-select"><option value="">Tümü</option><option value="1">Aktif</option><option value="0">Pasif</option></select></div><div class="col-md-4"><label class="form-label">Arama</label><input id="fSearch" class="form-control" placeholder="Soru/Cevap ara..."></div></div></div></div>
  <div class="card"><div class="card-body"><div class="table-responsive"><table class="table" id="tbl"><thead><tr><th>Başlık</th><th>Yeterlilik</th><th>TR Soru</th><th>TR Cevap</th><th>EN Cevap</th><th>Uz.</th><th>Durum</th><th>İşlem</th></tr></thead><tbody><tr><td colspan="8" class="text-muted">Yükleniyor...</td></tr></tbody></table></div></div></div>

  <div class="card mt-3"><div class="card-body"><h5>Toplu Pattern Giriş</h5><div class="row g-3"><div class="col-md-4"><label class="form-label">Başlık *</label><select id="bulkCategory" class="form-select"><option value="">Seçiniz...</option><?php foreach($categories as $c): ?><option value="<?=htmlspecialchars($c['id'])?>"><?=htmlspecialchars($c['name'])?></option><?php endforeach; ?></select></div><div class="col-md-8 d-flex align-items-end gap-2"><button class="btn btn-outline-primary" id="parseBulk">Ayrıştır</button><button class="btn btn-success" id="saveBulk">Onayla ve Kaydet</button></div></div><textarea id="bulkPattern" class="form-control mt-3" rows="10" placeholder="### WORD&#10;TR_SORU: ...&#10;EN_QUESTION: ...&#10;TR_CEVAP: ...&#10;EN_ANSWER: ...&#10;NOTE: ..."></textarea><div id="bulkPreview" class="mt-3"></div></div></div>
</div>

<div class="modal fade" id="m" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="mt">Soru</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form id="f"><input type="hidden" name="id" id="id"><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Başlık *</label><select class="form-select" name="category_id" id="category_id" required><option value="">Seçiniz...</option><?php foreach($categories as $c): ?><option value="<?=htmlspecialchars($c['id'])?>"><?=htmlspecialchars($c['name'])?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Yeterlilik</label><select class="form-select" name="qualification_id" id="qualification_id"><option value="">Opsiyonel</option><?php foreach($qualifications as $q): ?><option value="<?=htmlspecialchars($q['id'])?>"><?=htmlspecialchars($q['name'])?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">🇹🇷 Soru Metni *</label><textarea class="form-control" name="question_text" id="question_text" required></textarea></div><div class="col-12"><label class="form-label">🇬🇧 Question Text</label><textarea class="form-control" name="question_text_en" id="question_text_en"></textarea></div><div class="col-md-6"><label class="form-label">🇹🇷 Doğru Cevap *</label><input class="form-control" name="answer_text" id="answer_text" required></div><div class="col-md-6"><label class="form-label">🇬🇧 Correct Answer</label><input class="form-control" name="answer_text_en" id="answer_text_en"></div><div class="col-md-4"><label class="form-label">Sıra</label><input type="number" class="form-control" name="order_index" id="order_index" value="0"></div><div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" checked><label class="form-check-label" for="is_active">Aktif</label></div></div><div class="col-12"><label class="form-label">Not</label><textarea class="form-control" name="notes" id="notes"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">İptal</button><button class="btn btn-primary" type="submit">Kaydet</button></div></form></div></div></div>

<?php $extra_js=<<<'JS'
<script>
$(function(){
 const ep='../ajax/word-game-questions.php',m=bootstrap.Modal.getOrCreateInstance(document.getElementById('m'));
 const esc=v=>$('<div>').text(v??'').html();
 const api=(a,method='GET',data={})=>window.appAjax({url:ep+'?action='+encodeURIComponent(a),method,data,dataType:'json'});
 let bulkItems=[];
 async function load(){const r=await api('list_questions','GET',{category_id:$('#fCategory').val()||'',qualification_id:$('#fQualification').val()||'',is_active:$('#fActive').val()||'',search:$('#fSearch').val()||''}); if(!r.success)return; const rows=r.data?.questions||[]; if(!rows.length){$('#tbl tbody').html('<tr><td colspan="8" class="text-muted">Kayıt yok.</td></tr>'); return;} $('#tbl tbody').html(rows.map(x=>`<tr><td>${esc(x.category_name||'-')}</td><td>${esc(x.qualification_name||'-')}</td><td>${esc(x.question_text||'')}</td><td>${esc(x.answer_text||'')}</td><td>${esc(x.answer_text_en||'-')}</td><td>${esc(x.answer_length||0)}</td><td>${Number(x.is_active)===1?'<span class="badge text-bg-success">Aktif</span>':'<span class="badge text-bg-secondary">Pasif</span>'}</td><td><button class="btn btn-sm btn-outline-primary e" data-id="${esc(x.id)}"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-secondary t" data-id="${esc(x.id)}" data-a="${Number(x.is_active)===1?1:0}"><i class="bi bi-toggle-${Number(x.is_active)===1?'off':'on'}"></i></button> <button class="btn btn-sm btn-outline-danger d" data-id="${esc(x.id)}"><i class="bi bi-trash"></i></button></td></tr>`).join('')); }
 $('#addBtn').on('click',()=>{$('#f')[0].reset();$('#id').val('');$('#order_index').val('0');$('#is_active').prop('checked',true);m.show();});
 $('#fCategory,#fQualification,#fActive').on('change',load); $('#fSearch').on('input',()=>{clearTimeout(window.__wgs);window.__wgs=setTimeout(load,200)});
 $(document).on('click','.e',async function(){const r=await api('get_question','GET',{id:$(this).data('id')}); if(!r.success)return; const q=r.data.question; Object.keys(q).forEach(k=>$('#'+k).val(q[k]??'')); $('#is_active').prop('checked',Number(q.is_active)===1); m.show();});
 $('#f').on('submit',async function(e){e.preventDefault();const id=$('#id').val();const r=await api(id?'update_question':'create_question','POST',$(this).serialize()); if(!r.success){await window.showAppAlert({title:'Hata',message:r.message||'İşlem başarısız',type:'error'}); return;} m.hide(); load();});
 $(document).on('click','.t',async function(){await api('toggle_active','POST',{id:$(this).data('id'),is_active:String($(this).data('a'))==='1'?0:1}); load();});
 $(document).on('click','.d',async function(){await api('delete_question','POST',{id:$(this).data('id')}); load();});

 $('#parseBulk').on('click',async function(){const r=await api('parse_bulk_pattern','POST',{pattern:$('#bulkPattern').val()}); if(!r.success)return; bulkItems=(r.data.items||[]).map(x=>x.record); const p=(r.data.items||[]).map(x=>`<li class="${x.valid?'text-success':'text-danger'}">#${x.index+1} ${x.valid?'Geçerli':('Hatalı: '+(x.errors||[]).join(', '))}</li>`).join(''); $('#bulkPreview').html('<ul class="mb-0">'+p+'</ul>');});
 $('#saveBulk').on('click',async function(){const cid=$('#bulkCategory').val(); if(!cid){await window.showAppAlert({title:'Hata',message:'Başlık seçiniz',type:'error'});return;} const r=await api('create_bulk_questions','POST',{category_id:cid,items:JSON.stringify(bulkItems)}); if(!r.success){await window.showAppAlert({title:'Hata',message:r.message||'Kaydedilemedi',type:'error'});return;} await window.showAppAlert({title:'Başarılı',message:`${r.data.created_count||0} kayıt eklendi`,type:'success'}); load();});
 load();
});
</script>
JS; include '../includes/footer.php'; ?>
