<?php
require_once '../includes/config.php'; require_once '../includes/auth.php'; require_once '../includes/functions.php';
$user=require_auth(); $current_page='word-game-categories'; $page_title='Kelime Oyunu - Başlıklar';
include '../includes/header.php'; include '../includes/sidebar.php';
?>
<div class="container-fluid"><div class="page-header"><div><h2>Kelime Oyunu - Başlıklar</h2></div><div class="page-actions"><button class="btn btn-primary" id="addBtn"><i class="bi bi-plus-lg"></i> Yeni Başlık</button></div></div>
<div class="card mb-3"><div class="card-body"><div class="row g-3"><div class="col-md-4"><input id="search" class="form-control" placeholder="Başlık / slug ara..."></div><div class="col-md-3"><select id="active" class="form-select"><option value="">Tümü</option><option value="1">Aktif</option><option value="0">Pasif</option></select></div></div></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table" id="tbl"><thead><tr><th>Başlık</th><th>Slug</th><th>Durum</th><th>Sıra</th><th>İşlemler</th></tr></thead><tbody><tr><td colspan="5" class="text-muted">Yükleniyor...</td></tr></tbody></table></div></div></div></div>
<div class="modal fade" id="m" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="mt">Başlık</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form id="f"><input type="hidden" name="id" id="id"><div class="modal-body"><div class="mb-2"><label class="form-label">Başlık *</label><input class="form-control" name="name" id="name" required></div><div class="mb-2"><label class="form-label">Slug</label><input class="form-control" name="slug" id="slug"></div><div class="mb-2"><label class="form-label">Açıklama</label><textarea class="form-control" name="description" id="description"></textarea></div><div class="row g-2"><div class="col-6"><label class="form-label">Sıra</label><input type="number" class="form-control" name="order_index" id="order_index" value="0"></div><div class="col-6 d-flex align-items-end"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" checked><label class="form-check-label" for="is_active">Aktif</label></div></div></div></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal" type="button">İptal</button><button class="btn btn-primary" type="submit">Kaydet</button></div></form></div></div></div>
<?php $extra_js=<<<'JS'
<script>$(function(){const ep='../ajax/word-game-categories.php',m=bootstrap.Modal.getOrCreateInstance(document.getElementById('m'));const esc=v=>$('<div>').text(v??'').html();const api=(a,method='GET',data={})=>window.appAjax({url:ep+'?action='+encodeURIComponent(a),method,data,dataType:'json'});async function load(){const r=await api('list','GET',{search:$('#search').val()||'',is_active:$('#active').val()||''});if(!r.success)return;const rows=r.data?.items||[];if(!rows.length){$('#tbl tbody').html('<tr><td colspan="5" class="text-muted">Kayıt yok.</td></tr>');return;}$('#tbl tbody').html(rows.map(x=>`<tr><td>${esc(x.name)}</td><td><code>${esc(x.slug)}</code></td><td>${Number(x.is_active)===1?'<span class="badge text-bg-success">Aktif</span>':'<span class="badge text-bg-secondary">Pasif</span>'}</td><td>${esc(x.order_index||0)}</td><td><button class="btn btn-sm btn-outline-primary e" data-id="${esc(x.id)}"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-secondary t" data-id="${esc(x.id)}" data-a="${Number(x.is_active)===1?1:0}"><i class="bi bi-toggle-${Number(x.is_active)===1?'off':'on'}"></i></button> <button class="btn btn-sm btn-outline-danger d" data-id="${esc(x.id)}"><i class="bi bi-trash"></i></button></td></tr>`).join(''));}
$('#addBtn').on('click',()=>{$('#f')[0].reset();$('#id').val('');$('#order_index').val('0');$('#is_active').prop('checked',true);m.show();});$('#search').on('input',()=>{clearTimeout(window.__wgc);window.__wgc=setTimeout(load,200)});$('#active').on('change',load);
$(document).on('click','.e',async function(){const r=await api('get','GET',{id:$(this).data('id')});if(!r.success)return;const x=r.data.item;$('#id').val(x.id);$('#name').val(x.name);$('#slug').val(x.slug);$('#description').val(x.description||'');$('#order_index').val(x.order_index||0);$('#is_active').prop('checked',Number(x.is_active)===1);m.show();});
$('#f').on('submit',async function(e){e.preventDefault();const id=$('#id').val();const r=await api(id?'update':'create','POST',$(this).serialize());if(!r.success){await window.showAppAlert({title:'Hata',message:r.message||'İşlem başarısız',type:'error'});return;}m.hide();load();});
$(document).on('click','.t',async function(){await api('toggle_active','POST',{id:$(this).data('id'),is_active:String($(this).data('a'))==='1'?0:1});load();});
$(document).on('click','.d',async function(){await api('delete','POST',{id:$(this).data('id')});load();});
load();});</script>
JS; include '../includes/footer.php'; ?>
