<?php
require_once '../includes/config.php'; require_once '../includes/auth.php'; require_once '../includes/functions.php';
$user=require_auth(); $current_page='word-game-settings'; $page_title='Kelime Oyunu - Ayarlar';
include '../includes/header.php'; include '../includes/sidebar.php';
?>
<div class="container-fluid"><div class="page-header"><div><h2>Kelime Oyunu - Ayarlar</h2></div></div>
<div class="card"><div class="card-body"><form id="s"><div class="row g-3"><div class="col-md-4"><label class="form-label">Toplam hedef puan</label><input class="form-control" type="number" name="target_score" id="target_score" min="1"></div><div class="col-md-4"><label class="form-label">Harf başı puan</label><input class="form-control" type="number" name="points_per_char" id="points_per_char" min="1"></div><div class="col-md-4"><label class="form-label">Oyun süresi (sn)</label><input class="form-control" type="number" name="duration_seconds" id="duration_seconds" min="30"></div><div class="col-md-6"><label class="form-label">Minimum soru sayısı</label><input class="form-control" type="number" name="min_questions" id="min_questions" min="1"></div><div class="col-md-6"><label class="form-label">Maksimum soru sayısı</label><input class="form-control" type="number" name="max_questions" id="max_questions" min="1"></div></div><hr><h6>Soru havuzu karakter uzunlukları</h6><div id="lens" class="row row-cols-2 row-cols-md-4 g-2"></div><button class="btn btn-primary mt-3" type="submit">Kaydet</button></form></div></div></div>
<?php $extra_js=<<<'JS'
<script>$(function(){const ep='../ajax/word-game-settings.php';const api=(a,method='GET',data={})=>window.appAjax({url:ep+'?action='+encodeURIComponent(a),method,data,dataType:'json'});let counts={};function renderLens(allowed){const set=new Set((allowed||[]).map(Number));const wrap=$('#lens');wrap.empty();for(let i=3;i<=24;i++){const c=counts[i]||0;wrap.append(`<div class="col"><label class="form-check border rounded p-2 d-block"><input class="form-check-input me-2" type="checkbox" name="allowed_lengths[]" value="${i}" ${set.has(i)?'checked':''}>${i} karakter — ${c} soru</label></div>`);}}
async function load(){const r=await api('get');if(!r.success)return;const s=r.data.settings||{};counts=r.data.length_counts||{};$('#target_score').val(s.target_score||10000);$('#points_per_char').val(s.points_per_char||100);$('#min_questions').val(s.min_questions||8);$('#max_questions').val(s.max_questions||14);$('#duration_seconds').val(s.duration_seconds||400);renderLens(s.allowed_lengths||[]);}$('#s').on('submit',async function(e){e.preventDefault();const r=await api('save','POST',$(this).serialize());if(!r.success){await window.showAppAlert({title:'Hata',message:r.message||'Kaydedilemedi',type:'error'});return;}await window.showAppAlert({title:'Başarılı',message:'Ayarlar kaydedildi',type:'success'});load();});load();});</script>
JS; include '../includes/footer.php'; ?>
