<?php
require_once '../includes/config.php'; require_once '../includes/auth.php'; require_once '../includes/functions.php';
$user=require_auth(); $current_page='word-game-mappings'; $page_title='Kelime Oyunu - Eşleştirmeler';
include '../includes/header.php'; include '../includes/sidebar.php';
?>
<div class="container-fluid"><div class="page-header"><div><h2>Kelime Oyunu - Başlık / Yeterlilik Eşleştirme</h2></div></div><div id="list"></div></div>
<?php $extra_js=<<<'JS'
<script>$(function(){const ep='../ajax/word-game-mappings.php';const api=(a,method='GET',data={})=>window.appAjax({url:ep+'?action='+encodeURIComponent(a),method,data,dataType:'json'});const esc=v=>$('<div>').text(v??'').html();const num=v=>Number(v||0);let st={categories:[],qualifications:[],mapping:{}};
function render(){const w=$('#list');w.empty();(st.categories||[]).forEach(c=>{const selected=new Set(st.mapping?.[c.id]||[]);const q=(st.qualifications||[]).map(x=>`<div class="form-check"><input class="form-check-input q" type="checkbox" value="${esc(x.id)}" id="m_${esc(c.id)}_${esc(x.id)}" ${selected.has(String(x.id))?'checked':''}><label class="form-check-label" for="m_${esc(c.id)}_${esc(x.id)}">${esc(x.name)}</label></div>`).join('');const warn='<div class="alert alert-info py-2 mt-2 mb-0 small">Bu başlıktaki tüm sorular, aşağıda seçili yeterliliklerin ortak soru havuzudur.</div>';const names=c.qualification_names?esc(c.qualification_names):'<span class="text-danger">Eşleştirme yok</span>';w.append(`<div class="card mb-3" data-c="${esc(c.id)}"><div class="card-body"><div class="d-flex justify-content-between gap-3"><div><div class="fw-semibold">${esc(c.name)} ${Number(c.is_active)===1?'<span class="badge text-bg-success">Aktif</span>':'<span class="badge text-bg-secondary">Pasif</span>'}</div><div class="small text-muted"><code>${esc(c.slug)}</code></div></div><button class="btn btn-sm btn-primary s" data-c="${esc(c.id)}">Kaydet</button></div><div class="row g-2 mt-2"><div class="col-md-2"><div class="small text-muted">Toplam soru</div><strong>${num(c.question_count)}</strong></div><div class="col-md-2"><div class="small text-muted">Aktif soru</div><strong>${num(c.active_question_count)}</strong></div><div class="col-md-3"><div class="small text-muted">Oyun için uygun aktif</div><strong>${num(c.eligible_active_question_count)}</strong></div><div class="col-md-2"><div class="small text-muted">Havuz türü</div><strong>Ortak</strong></div><div class="col-md-3"><div class="small text-muted">Bağlı yeterlilikler</div><div>${names}</div></div></div>${warn}<div class="mt-3">${q}</div><div class="save-msg small mt-2"></div></div></div>`);});}
async function load(){const r=await api('list');if(!r.success)return;st={categories:r.data.categories||[],qualifications:r.data.qualifications||[],mapping:r.data.mapping||{}};render();}
$(document).on('click','.s',async function(){const btn=$(this),cid=btn.data('c'),card=btn.closest('[data-c]'),ids=[];card.find('.q:checked').each(function(){ids.push($(this).val());});const cat=(st.categories||[]).find(x=>String(x.id)===String(cid));if(cat&&Number(cat.is_active)===1&&ids.length===0){await window.showAppAlert({title:'Uyarı',message:'Aktif kategori için tüm yeterlilik seçimleri kaldırılamaz. Önce kategoriyi pasife alın veya en az bir yeterlilik seçin.',type:'warning'});return;}btn.prop('disabled',true);card.find('.save-msg').removeClass('text-success text-danger').text('Kaydediliyor...');const r=await api('save','POST',{category_id:cid,qualification_ids:ids});btn.prop('disabled',false);if(!r.success){let msg=r.message||'Kaydedilemedi.';if(r.data?.blocked_qualification_names?.length){msg+=` Bloklanan yeterlilikler: ${r.data.blocked_qualification_names.join(', ')}`;}card.find('.save-msg').addClass('text-danger').text(msg);await window.showAppAlert({title:'Hata',message:msg,type:'error'});return;}card.find('.save-msg').addClass('text-success').text(r.message||'Eşleştirmeler güncellendi.');await window.showAppAlert({title:'Başarılı',message:'Eşleştirmeler güncellendi.',type:'success'});await load();});
load();});</script>
JS; include '../includes/footer.php'; ?>
